[tox]
env_list = lint, py310, py311, py312, py313
skip_missing_interpreters = false

[testenv]
extras = test
pass_env =
    PROJ_*
commands = pytest {posargs}

[testenv:lint]
skip_install = true
deps = ruff
commands = ruff check

[testenv:pyright]
base_python = py311
extras = develop
commands = pyright
